# Generated by Django 4.1.3 on 2023-01-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_category',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_tags',
            field=models.JSONField(null=True, verbose_name='Tags'),
        ),
    ]
