# Generated by Django 4.1.3 on 2022-12-28 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='deleted_on',
            field=models.DateTimeField(max_length=20, null=True, verbose_name='Deleted Date-Time'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_pubdate',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 8, 3, 37, 432552, tzinfo=datetime.timezone.utc)),
        ),
    ]
