# Generated by Django 4.1.3 on 2023-01-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0002_remove_blogs_blog_category_blogs_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_tags',
            field=models.CharField(default=False, max_length=50, verbose_name='Blog Category'),
        ),
    ]
