# Generated by Django 4.1.3 on 2023-01-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0003_alter_blogs_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_tags',
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tags', models.CharField(max_length=100, verbose_name='Blog Category')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='untangled.blogs')),
            ],
        ),
    ]
