# Generated by Django 4.1.3 on 2022-12-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0004_alter_blogs_blog_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_pubdate',
            field=models.DateField(default=False),
        ),
    ]
