# Generated by Django 4.1.3 on 2023-01-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0005_blogs_blog_tags_delete_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_tags',
            field=models.CharField(max_length=255, verbose_name='Blog Category'),
        ),
    ]
