# Generated by Django 4.1.3 on 2023-01-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0006_alter_blogs_blog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_tags',
            new_name='blog_category',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_userid',
            new_name='blog_user',
        ),
    ]
