# Generated by Django 4.1.3 on 2023-01-01 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('untangled', '0007_alter_blogs_blog_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
