# Generated by Django 4.1.3 on 2023-01-04 05:35

from django.db import migrations, models
import untangled.models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0009_alter_blogs_blog_body_alter_blogs_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_thumbnail',
            field=models.ImageField(default='/media/blogpost_cover.jpg', upload_to=untangled.models.image_path),
        ),
    ]
