# Generated by Django 4.1.3 on 2023-01-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untangled', '0010_alter_blogs_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_description',
            field=models.TextField(default='', max_length=255, verbose_name='Blog Description'),
        ),
    ]
