# Generated by Django 4.1.3 on 2023-01-06 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('untangled', '0012_blogs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='likes',
            field=models.ManyToManyField(related_name='blog_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
